project:
  type: website

website:
  title: "Georgia's IS415 Experience"
  navbar:
    left: 
    - text: "Hands On Exercise"
      menu:
      - text: "Hands On Exercise 1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands On Exercise 2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
    - text: "In Class Exercise"
      menu:
      - text: "In Class Exercise 1"
        href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
      - text: "In Class Exercise 2"
        href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

